module.exports = {
  type: 'mysql',
  host: process.env.DB_HOST,
  port: +process.env.DB_PORT,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  // charset: 'utf8mb4',
  supportBigNumbers: true,
  bigNumberStrings: false,
  migrationsRun: false,
  synchronize: false,
  logging: process.env.APP_STAGE === 'development',
  entityPrefix: process.env.DB_ENTITY_PREFIX || '',
  entities: ['dist/**/*.entity.ts'],
  migrations: ['database/migrations/*.ts'],
  cli: {
    migrationsDir: 'database/migrations',
  },
};
