module.exports = {
  entities: [],
  keepConnectionAlive: true,
  type: 'mysql',
  host: process.env.DB_HOST,
  port: +process.env.DB_PORT,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE || '',
  charset: 'utf8mb4',
  supportBigNumbers: true,
  bigNumberStrings: false,
  entityPrefix: process.env.DB_ENTITY_PREFIX || '',
  subscribers: [],
  migrationsRun: false,
  synchronize: true,
  logging: process.env.APP_STAGE === 'dev' ? ['error'] : [],
  autoLoadEntities: true,
  // timezone: 'Z',
};
